# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1412bc06afaecb2060a05d6ab77f3bdec94443d8a40027ac6bff206dc8a047947a57acb36beb686ccbde2312399500b9498a1da9d3b6c38c9cea0865e5ec6400

test:
  secret_key_base: c2916222d407beffdac6ff8931e4cc75530e2c02482ad3634dbb7d48f7c09b43162df78597a044cfc383386bf6018d285194616d76e0014abea3245726dc95bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
